module.exports.SOCKET_CONNECTED = "SOCKET_CONNECTED";
module.exports.SOCKET_INIT_CHAT = "SOCKET_INIT_CHAT";

module.exports.SOCKET_SEND_MESSAGE = 'SOCKET_SEND_MESSAGE'
module.exports.SOCKET_RECIEVE_MESSAGE = 'SOCKET_RECIEVE_MESSAGE';

module.exports.SOCKET_USER_LOGIN = 'SOCKET_USER_LOGIN';
module.exports.SOCKET_USER_LOGIN_STATUS = 'SOCKET_USER_LOGIN_STATUS';

module.exports.SOCKET_PRESENCE_USERS_ADD = 'SOCKET_PRESENCE_USERS_ADD';
module.exports.SOCKET_PRESENCE_USERS_REMOVE = 'SOCKET_PRESENCE_USERS_REMOVE';