export const ADD_MESSAGE = 'ADD_MESSAGE';
export const SEND_MESSAGE = 'SEND_MESSAGE'
export const SEND_MESSAGE_LOADING = 'SEND_MESSAGE_LOADING';
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE';
export const INIT_MESSAGES = 'INIT_MESSAGES';
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';

export const SERVER_CONNECTED = 'SERVER_CONNECTED';

export const USER_LOGGING_IN = 'USER_LOGGING_IN';
export const USER_LOGGED_IN_SUCCESS = 'USER_LOGGED_IN_STATUS';
export const USER_LOGGED_IN_FAILURE = 'USER_LOGGED_IN_STATUS';
export const USER_LOGGED_IN_LOADING = 'USER_LOGGED_IN_LOADING';
export const USER_INIT = 'USER_INIT';

export const USERS_LIST_INIT = 'USERS_LIST_INIT';
export const USER_LIST_ADD = 'USER_LIST_ADD';
export const USER_LIST_REMOVE = 'USER_LIST_REMOVE';
