export const SOCKET_CONNECTED = "SOCKET_CONNECTED";
export const SOCKET_INIT_CHAT = "SOCKET_INIT_CHAT";

export const SOCKET_SEND_MESSAGE = 'SOCKET_SEND_MESSAGE'
export const SOCKET_RECIEVE_MESSAGE = 'SOCKET_RECIEVE_MESSAGE';

export const SOCKET_USER_LOGIN = 'SOCKET_USER_LOGIN';
export const SOCKET_USER_LOGIN_STATUS = 'SOCKET_USER_LOGIN_STATUS';

export const SOCKET_PRESENCE_USERS_ADD = 'SOCKET_PRESENCE_USERS_ADD';
export const SOCKET_PRESENCE_USERS_REMOVE = 'SOCKET_PRESENCE_USERS_REMOVE';